apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  grafana.ini: |-
    [server]
    protocol = http
    http_port = 3000
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    serve_from_sub_path = false

    [security]
    admin_user = admin
    admin_password = admin

    [auth.anonymous]
    enabled = false

    [log]
    mode = console
    level = info
