apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.admin.userSecretName }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  admin-user: {{ .Values.admin.userKey | b64enc }}
  admin-password: {{ .Values.admin.passwordKey | b64enc }}
