
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  destination:
    namespace: elasticsearch
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.11.1
    helm:
      valueFiles:
        - ../../helm-values/elasticsearch-values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
