
apiVersion: batch/v1
kind: Job
metadata:
  name: create-ilm-policy
  namespace: elasticsearch
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          command:
            - curl
            - -XPUT
            - -u
            - "elastic:changeme"
            - "http://elasticsearch-master:9200/_ilm/policy/delete-after-2days"
            - -H
            - "Content-Type: application/json"
            - -d
            - '{
                "policy": {
                  "phases": {
                    "hot": {
                      "actions": {
                        "rollover": {
                          "max_age": "1d"
                        }
                      }
                    },
                    "delete": {
                      "min_age": "2d",
                      "actions": {
                        "delete": {}
                      }
                    }
                  }
                }
              }'
      restartPolicy: OnFailure
