apiVersion: v1
kind: Service
metadata:
  name: pushgateway
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9091
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: pushgateway
