replicaCount: 1

image:
  repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
  tag: "v2.10.1"

serviceAccount:
  create: true
  name: ""

service:
  type: NodePort
  port: 8080
  nodePort: 30200

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

tolerations: []
