fullnameOverride: "kube-state-metrics"

service:
  type: NodePort
  nodePort: 31091  # pick a free port
  port: 8080

resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi
