{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-node-exporter.serviceAccountName" . }}
  labels:
    {{- include "prometheus-node-exporter.labels" . | nindent 4 }}
{{- end }}
