
replicas: 3
minimumMasterNodes: 2
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: certificate
    xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/tls.key
    xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/tls.crt
    xpack.security.transport.ssl.certificate_authorities: [ "/usr/share/elasticsearch/config/certs/ca.crt" ]
    xpack.license.self_generated.type: basic
    xpack.ml.enabled: false
    xpack.monitoring.collection.enabled: true
    indices.lifecycle.poll_interval: 5m
    cluster.routing.allocation.disk.threshold_enabled: true
    cluster.routing.allocation.disk.watermark.low: 85%
    cluster.routing.allocation.disk.watermark.high: 90%
    cluster.routing.allocation.disk.watermark.flood_stage: 95%
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
persistence:
  enabled: true
  storageClass: standard
podSecurityContext:
  fsGroup: 1000
readinessProbe:
  httpGet:
    path: /_cluster/health
    port: 9200
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 10
