
replicaCount: 1
elasticsearchHosts: "http://elasticsearch-master:9200"
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
readinessProbe:
  httpGet:
    path: /app/kibana
    port: 5601
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 10
