rbac:
  create: true

serviceAccount:
  create: true
  name: ""

service:
  type: NodePort
  port: 9100
  nodePort: 30100

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

tolerations:
  - operator: "Exists"
    