fullnameOverride: "node-exporter"

serviceAccount:
  create: true
  name: ""

service:
  type: NodePort
  port: 9100
  nodePort: 31090   # Choose a free port on your laptop

resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 100Mi

prometheus:
  monitor:
    enabled: true
    namespace: monitoring
    interval: 15s

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true
